import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { TransformControls } from 'three/addons/controls/TransformControls.js';
window.__formaStarted = true;

const $ = (s) => document.querySelector(s);
const viewport = $('#viewport');
const scene = new THREE.Scene(); scene.background = new THREE.Color(0xeef0f4);
const camera = new THREE.PerspectiveCamera(45, 1, .1, 1000); camera.position.set(7, 5.5, 8);
const renderer = new THREE.WebGLRenderer({ antialias:true, preserveDrawingBuffer:true }); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; viewport.appendChild(renderer.domElement);
const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping=true; controls.target.set(0,1,0);
const transform = new TransformControls(camera, renderer.domElement); scene.add(transform); transform.addEventListener('dragging-changed', e => controls.enabled=!e.value); transform.addEventListener('objectChange', syncInspector);
scene.add(new THREE.HemisphereLight(0xffffff,0x9ea7b5,2.2)); const key=new THREE.DirectionalLight(0xffffff,3); key.position.set(5,9,4); key.castShadow=true; scene.add(key);
const grid = new THREE.GridHelper(20,20,0xc7cad3,0xdfe1e7); grid.position.y=-.01; scene.add(grid);
const ground = new THREE.Mesh(new THREE.PlaneGeometry(20,20),new THREE.ShadowMaterial({opacity:.09})); ground.rotation.x=-Math.PI/2; ground.receiveShadow=true; scene.add(ground);
let selected=null, tool='select', idCounter=1; const objects=[];
const colors=['#6f6cff','#ff7b58','#55b5a1','#e8ad58','#d975aa'];
const geometryFor = type => ({box:new THREE.BoxGeometry(1.5,1.5,1.5),sphere:new THREE.SphereGeometry(1,32,20),cylinder:new THREE.CylinderGeometry(.8,.8,1.7,32),torus:new THREE.TorusGeometry(.75,.28,16,40)})[type];
function addObject(type='box', data={}) { const material=new THREE.MeshStandardMaterial({color:data.color||colors[(objects.length)%colors.length],metalness:data.metalness??.2,roughness:data.roughness??.4}); const mesh=new THREE.Mesh(geometryFor(type),material); mesh.name=data.name||`${type[0].toUpperCase()+type.slice(1)} ${idCounter++}`; mesh.castShadow=true; mesh.receiveShadow=true; mesh.userData.type=type; mesh.position.set(...(data.position||[0, type==='box'?0.75:1,0])); if(data.rotation) mesh.rotation.set(...data.rotation.map(v=>THREE.MathUtils.degToRad(v))); if(data.scale) mesh.scale.set(...data.scale); scene.add(mesh); objects.push(mesh); select(mesh); updateScene(); return mesh; }
function select(obj){ selected=obj; transform.detach(); if(obj && tool!=='select') transform.attach(obj); syncInspector(); updateScene(); }
function setTool(next){ tool=next; document.querySelectorAll('.tool-card').forEach(b=>b.classList.toggle('active',b.dataset.tool===next)); if(selected&&next!=='select'){transform.setMode(next==='translate'?'translate':next==='rotate'?'rotate':'scale');transform.attach(selected)}else transform.detach(); }
function syncInspector(){ const has=!!selected; $('#empty-inspector').classList.toggle('hidden',has); $('#inspector-content').classList.toggle('hidden',!has); $('#selection-label').textContent=has?'OBJECT':'NONE SELECTED'; if(!has)return; $('#object-name').value=selected.name; $('#selected-shape').style.background=selected.material.color.getStyle(); const vals={position:{x:selected.position.x,y:selected.position.y,z:selected.position.z},rotation:{x:THREE.MathUtils.radToDeg(selected.rotation.x),y:THREE.MathUtils.radToDeg(selected.rotation.y),z:THREE.MathUtils.radToDeg(selected.rotation.z)},scale:{x:selected.scale.x,y:selected.scale.y,z:selected.scale.z}}; document.querySelectorAll('[data-transform]').forEach(input=>{const [a,b]=input.dataset.transform.split('.');input.value=Number(vals[a][b].toFixed(2));}); $('#object-color').value='#'+selected.material.color.getHexString();$('#color-value').textContent=$('#object-color').value.toUpperCase();$('#object-metalness').value=selected.material.metalness;$('#metalness-value').textContent=selected.material.metalness.toFixed(2);$('#object-roughness').value=selected.material.roughness;$('#roughness-value').textContent=selected.material.roughness.toFixed(2); }
function updateScene(){ const tree=$('#scene-tree'); tree.innerHTML=objects.length?'':`<div class="tree-empty">Your scene is empty</div>`; objects.forEach(o=>{const row=document.createElement('button');row.className=`tree-row ${o===selected?'selected':''}`;row.innerHTML=`<span class="tree-icon"></span><span class="tree-name">${o.name}</span><span class="tree-type">${o.userData.type}</span>`;row.onclick=()=>select(o);tree.appendChild(row)});$('#object-count').textContent=`${objects.length} object${objects.length===1?'':'s'}`;$('#viewport-empty').style.display=objects.length?'none':'flex'; }
function removeSelected(){if(!selected)return; scene.remove(selected);selected.geometry.dispose();selected.material.dispose();objects.splice(objects.indexOf(selected),1);select(objects.at(-1)||null);toast('Object deleted');}
function serialize(){return {version:1,name:$('#project-name').value,objects:objects.map(o=>({name:o.name,type:o.userData.type,position:o.position.toArray(),rotation:[o.rotation.x,o.rotation.y,o.rotation.z].map(THREE.MathUtils.radToDeg),scale:o.scale.toArray(),color:'#'+o.material.color.getHexString(),metalness:o.material.metalness,roughness:o.material.roughness}))};}
function download(filename,data,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function save(){const data=serialize();localStorage.setItem('forma-project',JSON.stringify(data));$('#save-status').textContent='Saved locally · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});toast('Project saved to this browser');}
function load(data){objects.slice().forEach(o=>scene.remove(o));objects.length=0;idCounter=1;$('#project-name').value=data.name||'Untitled structure';(data.objects||[]).forEach(o=>addObject(o.type,o));select(null);updateScene();}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function frame(){if(!selected)return;const box=new THREE.Box3().setFromObject(selected),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length();controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(size*.9,size*.65,size*.9));camera.lookAt(center);}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addObject(b.dataset.add));
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=b.dataset.view;if(v==='top')camera.position.set(0,10,.01);else if(v==='front')camera.position.set(0,2,10);else camera.position.set(7,5.5,8);controls.target.set(0,1,0);});
$('#save-btn').onclick=save;$('#load-btn').onclick=()=>$('#load-input').click();$('#export-btn').onclick=()=>{download(`${$('#project-name').value||'forma-project'}.json`,JSON.stringify(serialize(),null,2));toast('Scene JSON exported');};$('#clear-btn').onclick=()=>{if(objects.length&&confirm('Clear the whole scene?')){objects.slice().forEach(o=>scene.remove(o));objects.length=0;select(null);updateScene();}};$('#delete-btn').onclick=removeSelected;$('#focus-btn').onclick=frame;$('#grid-btn').onclick=()=>grid.visible=!grid.visible;$('#camera-btn').onclick=()=>{const dataUrl=renderer.domElement.toDataURL('image/png');const a=document.createElement('a');a.href=dataUrl;a.download='forma-viewport.png';a.click();};
$('#object-name').oninput=e=>{if(selected){selected.name=e.target.value||'Object';updateScene();}};document.querySelectorAll('[data-transform]').forEach(input=>input.oninput=e=>{if(!selected)return;const [a,b]=input.dataset.transform.split('.');let val=Number(e.target.value)||0;if(a==='rotation')val=THREE.MathUtils.degToRad(val);selected[a][b]=val;});$('#object-color').oninput=e=>{if(selected){selected.material.color.set(e.target.value);syncInspector();}};['metalness','roughness'].forEach(k=>$('#object-'+k).oninput=e=>{if(selected){selected.material[k]=Number(e.target.value);$(`#${k}-value`).textContent=Number(e.target.value).toFixed(2);}});
renderer.domElement.addEventListener('pointerdown',e=>{if(tool!=='select')return;const rect=renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(objects)[0];select(hit?.object||null);});
document.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;const map={q:'select',w:'translate',e:'rotate',r:'scale'};if(map[e.key.toLowerCase()])setTool(map[e.key.toLowerCase()]);if(e.key.toLowerCase()==='f')frame();if(e.key==='Delete'||e.key==='Backspace')removeSelected();if(e.key==='1')addObject('box');if(e.key==='2')addObject('sphere');if(e.key==='3')addObject('cylinder');if(e.key==='4')addObject('torus');});
$('#load-input').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{load(JSON.parse(reader.result));toast('Project loaded')}catch{toast('That file is not a Forma project')}};reader.readAsText(file);};
const stored=localStorage.getItem('forma-project');if(stored)try{load(JSON.parse(stored));}catch{};function resize(){const r=viewport.getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false)}window.addEventListener('resize',resize);resize();
function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}animate();updateScene();
