watch_stylesheet: true
watch_config: true
debug: false
update_check: true
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: "None"
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 26
    padding:
      top: 5
      left: 0
      bottom: -1
      right: 0
    widgets:
      left: []
      center:
        # - "systray"
        - "komorebi_active_layout"
        - "komorebi_workspaces"
        - "cpu"
        - "memory"
        - "traffic"
        - "weather"
        - "clock"
        - "volume"
        - "media"
        - "notifications"
        - "wallpapers"
        - "disk"
        - "home_folder"
        - "server_monitor"
        - "todo"
        - "notes"
        # - "ip_info"
        - "scoop_updates"
        - "winget_updates"
        - "ai_chat"
      right: []
widgets:
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 1000
      cpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "exec cmd /k start C:\\Users\\nahid\\ms\\ms1\\asset\\yasb_reborn\\get_top_processes.ps1"
        on_middle: "exec cmd /c Taskmgr"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "exec cmd /c start C:\\Users\\nahid\\ms\\ms1\\test_project\\ollama-chat-app\\ollama_stop_models.ps1"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span class='download'>\udb81\udf2e {download_speed}</span><span class='upload'>{upload_speed} \udb81\udf37</span>"
      update_interval: 1000
      speed_unit: bytes
      menu:
        round_corners: false
        alignment: "center"
        direction: "down"
        offset_top: true
      callbacks:
        on_left: "toggle_menu"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        - "bsp"
        - "columns"
        - "rows"
        - "grid"
        - "scrolling"
        - "vertical_stack"
        - "horizontal_stack"
        - "ultrawide_vertical_stack"
        - "right_main_vertical_stack"
      layout_icons:
        bsp: "\uebeb"
        columns: "\uebf7"
        rows: "\uec01"
        grid: "\udb81\udf58"
        scrolling: "\uebf7"
        vertical_stack: "\uebee"
        horizontal_stack: "\uebf0"
        ultrawide_vertical_stack: "\uebee"
        right_main_vertical_stack: "\uebf1"
        monocle: "\uf50c"
        maximized: "\uf06f"
        floating: "\uf2d2"
        paused: "\udb83\udf89"
        tiling: "\udb81\ude40"
      callbacks:
        on_left: "toggle_layout_menu"
        on_middle: "toggle_tiling"
        on_right: "next_layout"
      layout_menu:
        blur: true
        round_corners: false
        alignment: "left"
        direction: "down"
        offset_top: true
        show_layout_icons: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "<span>\ueb96</span>"
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist}"
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "toggle_play_pause"
        on_right: "toggle_label"
      max_field_size:
        label: 30
        label_alt: 30
      hide_empty: true
      show_thumbnail: false
      scrolling_label:
        enabled: false
        update_interval_ms: 33
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
        blur: true
        round_corners: false
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: true
        thumbnail_corner_radius: 6
        thumbnail_size: 100
        max_title_size: 40
        max_artist_size: 20
        show_source: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\ue893"
      label_expanded: "\udb80\udd56"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      container_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "Low: {min_temp} | High: {max_temp} | Humidity: {humidity}"
      api_key: "f5bc02da05ce44f0b29231930251207" # Get your free API key from https://www.weatherapi.com/
      show_alerts: true
      update_interval: 600
      hide_decimal: true
      units: "metric"
      location: "Dhaka, Bangladesh"
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\ue312"
        cloudyNight: "\ue311"
        rainyDay: "\ue308"
        rainyNight: "\ue333"
        snowyIcyDay: "\ue30a"
        snowyIcyNight: "\ue335"
        blizzardDay: "\udb83\udf36"
        blizzardNight: "\udb83\udf36"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
        default: "\uebaa"
      weather_card:
        blur: true
        round_corners: false
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        icon_size: 40
        offset_top: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%I:%M %p}"
      label_alt: "{%A, %d %B %Y}"
      update_interval: 1000
      calendar:
        blur: true
        round_corners: false
        alignment: "center"
        direction: "down"
        offset_top: true
      callbacks:
        on_left: "toggle_calendar"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>{level}"
      volume_icons:
        - "\ue74f" # Icon for muted
        - "\ue992" # Icon for 0-10% volume
        - "\ue993" # Icon for 11-30% volume
        - "\ue994" # Icon for 31-60% volume
        - "\ue995" # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: false
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        offset_top: true
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf421</span>{count}"
      label_alt: "{count} Notification(s)"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_middle: "clear_notifications"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 10
        bottom: 0
        right: 10
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\nahid\\ms\\msBackups\\wallpaper" # Example path to folder with images
      change_automatically: false # Automatically change wallpaper
      update_interval: 60 # If change_automatically is true, update interval in seconds
      gallery:
        enabled: true
        blur: true
        image_width: 220
        image_per_page: 8
        show_buttons: false
        orientation: "portrait"
        image_spacing: 8
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: true
      run_after: # List of functions to run after wallpaper is updated
        - "wal -s -t -e -q -n -i {image}" # Example command to run after wallpaper is updated
        - "cmd.exe /c start /min pwsh ./yasb.ps1" # Example command to run after wallpaper is updated
      container_padding:
        top: 0
        left: 10
        bottom: 0
        right: 10
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [0, 0]
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span>\uf473</span>"
        label_alt: "<span>\uf473</span>"
        group_label:
          volume_labels: ["C", "D", "E", "F"]
          show_label_name: false 
          blur: True
          round_corners: True
          round_corners_type: "normal"
          border_color: "System"
          alignment: "right"
          direction: "down"
          distance: 6
        callbacks:
          on_left: "toggle_group"
        container_padding:
          top: 0
          left: 10
          bottom: 0
          right: 10
        label_shadow:
          enabled: false
          color: "black"
          radius: 3
          offset: [0, 0]
  home_folder:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\ue613</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "D:\\Downloads" }
      - { title: "msBackups", path: "C:\\Users\\nahid\\ms\\msBackups" }
      - { title: "Job", path: "C:\\Users\\nahid\\ms\\msBackups\\@JOB" }
      - { title: "ms1", path: "C:\\Users\\nahid\\ms\\ms1" }
      system_menu: false
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
      offset_top: 6
      offset_left: -50
      alignment: "left"
      direction: "down"
      container_padding:
        top: 0
        left: 10
        bottom: 0
        right: 10
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [0, 0]
  server_monitor:
    type: "yasb.server_monitor.ServerMonitor"
    options:
        label: "<span>\uf510</span>"
        label_alt: "{online}/{offline} of {total}"
        ssl_check: false
        ssl_verify: false
        ssl_warning: 10
        timeout: 2
        update_interval: 60
        desktop_notifications:
          ssl: false
          offline: true
        servers: [
          '192.168.0.101:5000',
          '192.168.0.101:5001',
          '192.168.0.101:5002',
          '192.168.0.101:5003',
        ]
        menu:
          blur: True
          round_corners: True
          round_corners_type: "normal"
          border_color: "System"
          alignment: "right"
          direction: "down"
        callbacks:
          on_left: "toggle_menu"
          on_right: "toggle_label"
        container_padding:
          top: 0
          left: 10
          bottom: 0
          right: 10
        label_shadow:
          enabled: false
          color: "black"
          radius: 3
          offset: [0, 0]
  todo:
    type: "yasb.todo.TodoWidget"
    options:
      label: "\uf0ae {count}/{completed}"
      label_alt: "\uf0ae Tasks: {count}"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
      icons:
        add: "\uf501 New Task"
        edit: "Edit"
        delete: "Delete"
        date: "\ue641"
        category: "\uf412"
        checked: "\udb80\udd34"
        unchecked: "\udb80\udd30"
        sort: "\ueab4"
        no_tasks: "\uf4a0"
      categories:
        default:
          label: "General"
        soon:
          label: "Complete soon"
        today:
          label: "End of day"
        urgent:
          label: "Urgent"
        important:
          label: "Important"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 10
        bottom: 0
        right: 10
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [0, 0]
  notes:
    type: "yasb.notes.NotesWidget"
    options:
      label: "<span>\udb82\udd0c</span> {count}"
      label_alt: "{count} notes"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        max_title_size: 150
        show_date_time: true
      icons:
        note: "\udb82\udd0c"
        delete: "\ueab8"
        copy: "\uebcc"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 10
        bottom: 0
        right: 10
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [0, 0]
  ip_info:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\udb81\udd9f</span> {data[ip]}"
      label_alt: "<span>\uf450</span> {data[city]} {data[region]}, {data[country]}"
      class_name: "ip-info-widget"
      exec_options:
        run_cmd: "curl.exe https://ipinfo.io"
        run_interval: 120000  # every 5 minutes
        return_format: "json"
        hide_empty: false
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec cmd /c ncpa.cpl" # open network settings
        on_right: "exec cmd /c start https://ipinfo.io/{data[ip]} " # open ipinfo in browser
      container_padding:
        top: 0
        left: 10
        bottom: 0
        right: 10
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [0, 0]
  scoop_updates:
      type: "yasb.custom.CustomWidget"
      options:
        label: "<span>\uf0ab</span> {data[count]}"
        label_alt: "<span>\uf466</span> Scoop: {data[count]} packages"
        class_name: "scoop-widget"
        exec_options:
          run_cmd: "C:\\Users\\nahid\\ms\\ms1\\asset\\yasb_reborn\\x_scoop_count_package.bat"
          run_interval: 300000  # every 5 minutes
          return_format: "json"
          hide_empty: true
        callbacks:
          on_left: "exec powershell -Command \"Start-Process powershell -ArgumentList '-NoExit', '-Command', 'scoop update *' -Verb RunAs\""
          on_middle: "toggle_label"
          on_right: "exec cmd /c start https://scoop.sh"
        container_padding:
          top: 0
          left: 10
          bottom: 0
          right: 10
        label_shadow:
          enabled: false
          color: "black"
          radius: 3
          offset: [0, 0]
  winget_updates:
      type: "yasb.custom.CustomWidget"
      options:
        label: "<span>\uf0ab</span> {data[count]}"
        label_alt: "<span>\uf17a</span> Winget: {data[count]} packages"
        class_name: "winget-widget"
        exec_options:
          run_cmd: "C:\\Users\\nahid\\ms\\ms1\\asset\\yasb_reborn\\x_winget_count_package.bat"
          run_interval: 300000  # every 5 minutes
          return_format: "json"
          hide_empty: true
        callbacks:
          on_left: "exec powershell -Command \"Start-Process powershell -ArgumentList '-NoExit', '-Command', 'winget upgrade --all' -Verb RunAs\""
          on_middle: "toggle_label"
          on_right: "exec cmd /c start https://winget.run"
        container_padding:
          top: 0
          left: 10
          bottom: 0
          right: 10
        label_shadow:
          enabled: false
          color: "black"
          radius: 3
          offset: [0, 0]
  ai_chat:
    type: "yasb.ai_chat.AiChatWidget"
    options:
      label: "<span>\uf086</span>"
      chat:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_left: 0
        offset_top: 6
      icons:
        send: "\uf1d8"
        stop: "\uf04d"
        clear: "\uf1f8"
        assistant: "\udb81\ude74"
      notification_dot:
        enabled: false
        corner: "top_right"
        color: "red"
        margin: [ 0, 2 ]
      callbacks:
        on_left: "toggle_chat"
      providers:
        - provider: "Ollama"
          api_endpoint: "http://localhost:11434/v1"
          credential: "ollama"
          models: 
          - name: "gemma3:1b"
            label: "Gemma3"
      container_padding:
        top: 0
        left: 10
        bottom: 0
        right: 10
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [0, 0]

