import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  links: defineTable({
    name: v.optional(v.string()),
    group: v.optional(v.string()),
    urls: v.array(v.string()),
    url: v.string(),
    default_type: v.string(),
    text: v.optional(v.string()),
    icon_class: v.optional(v.string()),
    img_src: v.optional(v.string()),
    svg_code: v.optional(v.string()),
    width: v.optional(v.string()),
    height: v.optional(v.string()),
    color: v.optional(v.string()),
    background_color: v.optional(v.string()),
    border_radius: v.optional(v.string()),
    title: v.optional(v.string()),
    click_action: v.optional(v.string()),
    font_family: v.optional(v.string()),
    font_size: v.optional(v.string()),
    li_width: v.optional(v.string()),
    li_height: v.optional(v.string()),
    li_bg_color: v.optional(v.string()),
    li_hover_color: v.optional(v.string()),
    li_border_color: v.optional(v.string()),
    li_border_radius: v.optional(v.string()),
    hidden: v.optional(v.boolean()),
    collapsible: v.optional(v.boolean()),
    display_style: v.optional(v.string()),
    horizontal_stack: v.optional(v.boolean()),
    password_protect: v.optional(v.boolean()),
    top_name: v.optional(v.string()),
    top_bg_color: v.optional(v.string()),
    top_text_color: v.optional(v.string()),
    top_border_color: v.optional(v.string()),
    top_hover_color: v.optional(v.string()),
    popup_bg_color: v.optional(v.string()),
    popup_text_color: v.optional(v.string()),
    popup_border_color: v.optional(v.string()),
    popup_border_radius: v.optional(v.string()),
    horizontal_bg_color: v.optional(v.string()),
    horizontal_text_color: v.optional(v.string()),
    horizontal_border_color: v.optional(v.string()),
    horizontal_hover_color: v.optional(v.string()),
    top_width: v.optional(v.string()),
    top_height: v.optional(v.string()),
    top_font_family: v.optional(v.string()),
    top_font_size: v.optional(v.string()),
    horizontal_width: v.optional(v.string()),
    horizontal_height: v.optional(v.string()),
    horizontal_font_family: v.optional(v.string()),
    horizontal_font_size: v.optional(v.string()),
  }),

  sidebar_buttons: defineTable({
    id: v.string(),
    name: v.string(),
    display_type: v.string(),
    icon_class: v.optional(v.string()),
    img_src: v.optional(v.string()),
    svg_code: v.optional(v.string()),
    url: v.string(),
    has_notification: v.boolean(),
    text_color: v.string(),
    bg_color: v.string(),
    hover_color: v.string(),
    border_color: v.string(),
    border_radius: v.string(),
    font_size: v.string(),
    notification_api: v.optional(v.string()),
    mark_seen_api: v.optional(v.string()),
  }),
});
