general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follows_focus: false

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: true

  # Whether to show floating windows as always on top.
  show_floating_on_top: false

  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # Whether to center new floating windows.
  center_new_floating_windows: false

  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "unchanged"

gaps:
  # Gap between adjacent windows.
  inner_gap: "0px"

  # Gap between windows and the screen edge.
  outer_gap: "1px"

# Highlight active/inactive windows with a colored border.
# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: "#00f200"

  inactive:
    enabled: false
    color: "#ff0000"

bar:
  height: "36px"
  position: "top"
  always_on_top: false
  opacity: 1.0
  background: "#475875"
  foreground: "#ffffff"
  font_family: "Segoe UI"
  font_size: "13px"
  padding: "4px 6px"
  offset_x: 0
  offset_y: 0
  border_radius: 0

  components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"


  components_center:
    - type: "window title"

  components_right:

    - type: "text"
      text: "E" 
      left_click_command: "exec C:\\ms1\\mypygui_import\\edit_files.py"
      background: "#000"
      foreground: "#fff"
      margin: 0 2 # Moves it left on top of the previous component
      padding: 5 5
      border_width: "1"
      border_color: "#fff"

    - type: "text"
      text: "Terminal" 
      left_click_command: "exec pwsh"
      right_click_command: "exec cmd"
      background: "#000"
      foreground: "#fff"
      margin: 0 2 # Moves it left on top of the previous component
      padding: 5 5
      border_width: "1"
      border_color: "#fff"

    - type: "text"
      text: "Sync" 
      left_click_command: "exec 'C://ms1//sync.ps1'"
      background: "#005900"
      foreground: "#fff"
      margin: 0 2 # Moves it left on top of the previous component
      padding: 5 5
      border_width: "1"
      border_color: "#fff"
      
    # - type: "cpu" #!cpu
    #   label: "CPU: {percent_usage}%"
    #   refresh_interval_ms: 1000
    #   padding: "5px 5px"
    #   background: "#3c8aff"
    #   foreground: "#000"
    #   font_family: "Comic Sans MS"
    #   font_size: "13px"
    #   font_weight: 950

    # - type: "gpu" #!gpu
    #   label: "GPU: {percent_usage}%"
    #   refresh_interval_ms: 1000
    #   padding: "5px 5px"
    #   background: "#00f200"
    #   foreground: "#000"
    #   font_family: "Comic Sans MS"
    #   font_size: "13px"
    #   font_weight: 950

    # - type: "system tray"

    - type: "tiling direction" #!tiling dir
      label_horizontal: "⮂"
      label_vertical: "⮁"
      background: "#ffffff33"
      margin: "0 4px"
      padding: "0 8px"

    - type: "binding mode" #!binding mode
      background: "#ffffff33"
      margin: "0 4px 0 0"
      padding: "0 8px"
      
    - type: "clock" #!clock
      padding: "5px 5px"
      background: "#ffffff"
      foreground: "#000"
      font_family: "Comic Sans MS"
      font_size: "13px"
      font_weight: 950
      # Documentation on formatting date/time string:
      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      time_formatting: "hh:mm:ss tt  ddd MMM d"

workspaces:
  - name: "1"
    display_name: "Main"
  - name: "2"
    display_name: "P"
  - name: "3"
    display_name: "G"
  - name: "4"
  - name: "5"

window_rules:
  #! Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  # - command: "set floating"
  #   match_class_name: "#xxxxxx"

  #! Do not manage picture-in-picture windows for browsers. Note that the default is for
  #! English; change `match_title` to the window's title if you use another language.
  #! Task Manager requires admin privileges to manage and should be ignored unless running
  #! the WM as admin.
  - command: "ignore" #!different from the rest
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"
    match_title: "[Pp]icture.in.[Pp]icture"

  - command: "ignore"
    match_class_name: "#32770"

  - command: "ignore"
    match_class_name: "CASCADIA_HOSTING_WINDOW_CLASS"
    
  - command: "ignore"
    match_class_name: "ConsoleWindowClass"

  - command: "ignore"
    match_process_name: "PowerToys.Settings"

  - command: "ignore"
    match_process_name: "PowerToys.Settings"

  - command: "ignore"
    match_process_name: "SnippingTool"

  - command: "ignore"
    match_process_name: "python"

  - command: "ignore"
    match_process_name: "PotPlayerMini64"

  - command: "ignore"
    match_process_name: "fdm"

  - command: "ignore"
    match_process_name: "qbittorrent"

  - command: "ignore"
    match_process_name: "RadeonSoftware"

  - command: "ignore"
    match_title: "WhatsApp"

  - command: "ignore"
    match_title: "Task Manager"

  - command: "ignore"
    match_class_name: "Qt5152QWindowIcon"

  - command: "ignore"
    match_class_name: "TWizardForm"
    
  - command: "ignore"
    match_process_name: "Riot Client"

  #! Some applications (eg. Steam) have borders that extend past the normal border size.
  #! - command: "resize borders 0px 0px 0px -500px"    #? top right bottom left
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

  - command: "set width 520px"
    match_process_name: "rssguard"
    
  - command: "set width 520px"
    match_title: "Microsoft Store"


  # - command: "move to workspace 2"
  #   match_process_name: "VALORANT-Win64-Shipping"

#!here only this 2 application will be splitted horizontally
  # - command: "tiling direction vertical"
  #   match_process_name: "rssguard"
 




binding_modes:
  - name: "resize"
    keybindings:
      #! Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        bindings: ["H", "Left"]
      - command: "resize width +2%"
        bindings: ["L", "Right"]
      - command: "resize height +2%"
        bindings: ["K", "Up"]
      - command: "resize height -2%"
        bindings: ["J", "Down"]
      #! Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  #! Resize focused window by a percentage or pixel amount.
  # - command: "resize width -2%"
  #   binding: "Alt+U"
  # - command: "resize width +2%"
  #   binding: "Alt+P"
  # - command: "resize height +2%"
  #   binding: "Alt+O"
  # - command: "resize height -2%"
  #   binding: "Alt+I"

  #! As an alternative to the resize keybindings above, resize mode enables resizing via
  #! HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - command: "binding mode resize"
    binding: "Alt+R"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "Alt+V"

  #! Change focus between floating / tiling windows.
  # - command: "focus mode toggle"
  #   binding: "Alt+Space"

  #! Change the focused window to be floating / tiling.
  # - command: "toggle floating"
  #   binding: "Alt+Shift+Space"

  #! Change the focused window to be maximized / unmaximized.
  # - command: "toggle maximized"
  #   binding: "Alt+X"

  #! Minimize focused window.
  - command: "set minimized"
    binding: "Alt+M"

  #! Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "Alt+T"
  - command: "focus workspace prev"
    binding: "Alt+Shift+T"

  #! Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"

  #! Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"

