model = "gpt-5.4-mini"
model_reasoning_effort = "medium"
[projects.'c:\users\nahid']
trust_level = "trusted"

[projects.'c:\users\nahid\desktop']
trust_level = "trusted"

[projects.'c:\@delta\ms1']
trust_level = "trusted"

[projects.'c:\@delta\db']
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4

[windows]
sandbox = "elevated"

[plugins."convex@openai-curated"]
enabled = true
