rclone_flags = [
  "--ask-password",
"--auto-confirm", 
"--backup-dir string", 
"--bind string", 
"--buffer-size SizeSuffix  ", 
"--bwlimit BwTimetable", 
"--bwlimit-file BwTimetable", 
"--ca-cert stringArray", 
"--cache-dir string ", 
"--check-first", 
"--checkers int", 
"-c, --checksum", 
"--client-cert string ", 
"--client-key string", 
"--color string", 
"--compare-dest stringArray", 
"--config string", 
"--contimeout Duration", 
"--copy-dest stringArray", 
"--cpuprofile string", 
"--cutoff-mode string ", 
"--default-time Time", 
"--delete-after", 
"--delete-before", 
"--delete-during", 
"--delete-excluded  ", 
"--disable string", 
"--disable-http-keep-alives", 
"--disable-http2", 
"-n, --dry-run", 
"--dscp string", 
"--dump DumpFlags", 
"--dump-bodies", 
"--dump-headers", 
"--error-on-no-transfer", 
"--exclude stringArray", 
"--exclude-from stringArray", 
"--exclude-if-present stringArray", 
"--expect-continue-timeout Duration", 
"--fast-list  ", 
"--files-from stringArray  ", 
"--files-from-raw stringArray", 
"-f, --filter stringArray ", 
"--filter-from stringArray ", 
"--fs-cache-expire-duration Duration  ", 
"--fs-cache-expire-interval Duration  ", 
"--header stringArray ", 
"--header-download stringArray  ", 
"--header-upload stringArray", 
"--human-readable", 
"--ignore-case", 
"--ignore-case-sync ", 
"--ignore-checksum  ", 
"--ignore-errors", 
"--ignore-existing  ", 
"--ignore-size", 
"-I, --ignore-times", 
"--immutable  ", 
"--include stringArray", 
"--include-from stringArray", 
"--inplace", 
"-i, --interactive", 
"--kv-lock-time Duration", 
"--log-file string  ", 
"--log-format string", 
"--log-level string ", 
"--log-systemd", 
"--low-level-retries int", 
"--max-age Duration ", 
"--max-backlog int  ", 
"--max-delete int", 
"--max-delete-size SizeSuffix", 
"--max-depth int", 
"--max-duration Duration", 
"--max-size SizeSuffix", 
"--max-stats-groups int", 
"--max-transfer SizeSuffix ", 
"--memprofile string", 
"-M, --metadata", 
"--metadata-exclude stringArray ", 
"--metadata-exclude-from stringArray  ", 
"--metadata-filter stringArray  ", 
"--metadata-filter-from stringArray", 
"--metadata-include stringArray ", 
"--metadata-include-from stringArray  ", 
"--metadata-set stringArray", 
"--min-age Duration ", 
"--min-size SizeSuffix", 
"--modify-window Duration  ", 
"--multi-thread-cutoff SizeSuffix", 
"--multi-thread-streams int", 
"--no-check-certificate", 
"--no-check-dest", 
"--no-console ", 
"--no-gzip-encoding ", 
"--no-traverse", 
"--no-unicode-normalization", 
"--no-update-modtime", 
"--order-by string  ", 
"--password-command SpaceSepList", 
"-P, --progress", 
"--progress-terminal-title ", 
"-q, --quiet ", 
"--rc", 
"--rc-addr stringArray", 
"--rc-allow-origin string  ", 
"--rc-baseurl string", 
"--rc-cert string", 
"--rc-client-ca string", 
"--rc-enable-metrics", 
"--rc-files string  ", 
"--rc-htpasswd string ", 
"--rc-job-expire-duration Duration", 
"--rc-job-expire-interval Duration", 
"--rc-key string", 
"--rc-max-header-bytes int ", 
"--rc-min-tls-version string", 
"--rc-no-auth ", 
"--rc-pass string", 
"--rc-realm string  ", 
"--rc-salt string", 
"--rc-serve", 
"--rc-server-read-timeout Duration", 
"--rc-server-write-timeout Duration", 
"--rc-template string ", 
"--rc-user string", 
"--rc-web-fetch-url string ", 
"--rc-web-gui ", 
"--rc-web-gui-force-update ", 
"--rc-web-gui-no-open-browser", 
"--rc-web-gui-update", 
"--refresh-times", 
"--retries int", 
"--retries-sleep Duration  ", 
"--server-side-across-configs", 
"--size-only  ", 
"--stats Duration", 
"--stats-file-name-length int", 
"--stats-log-level string  ", 
"--stats-one-line", 
"--stats-one-line-date", 
"--stats-one-line-date-format string  ", 
"--stats-unit string", 
"--streaming-upload-cutoff SizeSuffix ", 
"--suffix string", 
"--suffix-keep-extension", 
"--syslog", 
"--syslog-facility string  ", 
"--temp-dir string  ", 
"--timeout Duration ", 
"--tpslimit float", 
"--tpslimit-burst int ", 
"--track-renames", 
"--track-renames-strategy string", 
"--transfers int", 
"-u, --update", 
"--use-cookies",
"--use-json-log",
"--use-mmap",
"--use-server-modtime ",
"--user-agent string",
"-v, --verbose count",
"--multi-thread-write-buffer-size SizeSuffix ",
    # Add more flags here
]

while True:
    input_text = input("Enter your filter text (press Enter to exit): ")
    
    if not input_text:
        break
    
    filtered_flags = [flag for flag in rclone_flags if input_text in flag]
    
    print("".join([f'"{flag}" ' for flag in filtered_flags]))
